### PR TITLE
jerry: pass and enable jerry-test-suite

### LINKED ISSUE #234: jerry: jerry-test-suite failed
run ./tools/run-tests.py --jerry-test-suite under deps/jerry

### PR DESCRIPTION
**Pull request by algebrait**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
    jerry-test-suite pass now
- [ ] documentation is changed or added

This PR will fix #234

### CODE REVIEW

**Comment by legendecas** [comment]
Looks like jerry-test-suite is not enabled on CI?

**Comment by algebrait** [comment]
> Sounds like jerry-test-suite is not enabled on CI?

Both jerry-tests and jerry-test-suite are not enabled now.
jerry-tests failed by #386

**Comment by algebrait** [comment]
```
/home/travis/build/Rokid/ShadowNode/deps/jerry/jerry-core/api/jerry.c:2942:42: error: unused parameter ‘free_hint’ [-Werror=unused-parameter]
                                    void *free_hint, /**< hint params of buffer free callback */
```
It seems #421 compile failed for minimal profile

**Comment by algebrait** [comment]
CI time
PR:
 Ran for 22 min 14 sec
 Total time 36 min 56 sec
push:
 Ran for 15 min 12 sec
 Total time 34 min 49 sec
Is it acceptable? @yorkie

**Comment by yorkie** [comment]
A little bit long, how about checking the PR changes, and run jerry tests only if the jerry source is included?
